import random
import statistics

import optuna
import simpy

from src import config
from src.sim.processes import (
    burger_cook_loop,
    customer_arrivals,
    fry_cook_loop,
    ice_cream_cook_loop,
    inventory_manager,
)
from src.sim.restaurant import FastFoodRestaurant

N_SEEDS = 10
N_TRIALS = 500


def run_sim_for_optuna(cashiers, burger_cooks, fries_cooks, ice_cream_cooks, n_seeds):
    """Runs a batch of simulations with specific staffing and returns the average profit.

    Args:
        cashiers (int): The number of active cashiers.
        burger_cooks (int): The number of active burger cooks.
        fries_cooks (int): The number of active fry cooks.
        ice_cream_cooks (int): The number of active ice cream cooks.
        n_seeds (int): The number of random simulation days to average across.

    Returns:
        float: The average calculated profit across all simulated days.
    """
    profits = []

    for seed in range(n_seeds):
        random.seed(seed)
        env = simpy.Environment()
        stats = {
            "wait_times": [],
            "wasted_burgers": [],
            "wasted_fries": [],
            "wasted_ice_cream": [],
            "balked": [],
            "reneged": [],
            "captured_revenue": [],
            "lost_revenue": [],
        }

        restaurant = FastFoodRestaurant(
            env,
            num_cashiers=cashiers,
            num_burger_cooks=burger_cooks,
            num_fries_cooks=fries_cooks,
            num_ice_cream_cooks=ice_cream_cooks,
        )

        for _ in range(burger_cooks):
            env.process(burger_cook_loop(env, restaurant))
        for _ in range(fries_cooks):
            env.process(fry_cook_loop(env, restaurant))
        for _ in range(ice_cream_cooks):
            env.process(ice_cream_cook_loop(env, restaurant))

        env.process(customer_arrivals(env, restaurant, stats))
        env.process(inventory_manager(env, restaurant, stats))

        env.run(until=config.SIM_TIME)

        revenue = sum(stats["captured_revenue"])
        sim_hours = config.SIM_TIME / 3600.0

        cost_staff = (
            cashiers * config.WAGE_CASHIER
            + burger_cooks * config.WAGE_BURGER_COOK
            + fries_cooks * config.WAGE_FRIES_COOK
            + ice_cream_cooks * config.WAGE_ICE_CREAM_COOK
        ) * sim_hours

        waste_cost = (
            (len(stats["wasted_burgers"]) * config.COST_WASTED_BURGER)
            + (len(stats["wasted_fries"]) * config.COST_WASTED_FRIES)
            + (len(stats["wasted_ice_cream"]) * config.COST_WASTED_ICE_CREAM)
        )

        profit = revenue - (cost_staff + waste_cost)
        profits.append(profit)

    return statistics.mean(profits)


def objective(trial):
    """The objective function used by Optuna to maximize profit.

    Args:
        trial (optuna.trial.Trial): A specific set of hyperparameters proposed by Optuna.

    Returns:
        float: The average profit generated by the proposed hyperparameters.
    """
    cashiers = trial.suggest_int("cashiers", 1, 5)
    burger_cooks = trial.suggest_int("burger_cooks", 1, 5)
    fries_cooks = trial.suggest_int("fries_cooks", 1, 3)
    ice_cream_cooks = trial.suggest_int("ice_cream_cooks", 1, 3)

    config.TARGET_BURGER_INV = trial.suggest_int("target_burger_inv", 2, 15)
    config.TARGET_FRIES_INV = trial.suggest_int("target_fries_inv", 4, 20)
    config.TARGET_ICE_CREAM_INV = trial.suggest_int("target_ice_cream_inv", 2, 15)

    avg_profit = run_sim_for_optuna(
        cashiers, burger_cooks, fries_cooks, ice_cream_cooks, N_SEEDS
    )

    return avg_profit


if __name__ == "__main__":
    print("Starting AI Hyperparameter Optimization...")
    print(
        f"Testing {N_TRIALS} combinations, averaging {N_SEEDS} seeds per combination."
    )

    optuna.logging.set_verbosity(optuna.logging.WARNING)

    study = optuna.create_study(direction="maximize")

    study.optimize(objective, n_trials=N_TRIALS, show_progress_bar=True)

    print("\n" + "=" * 40)
    print("OPTIMIZATION COMPLETE")
    print(f"Maximum Expected Profit (Avg over {N_SEEDS} days): ${study.best_value:.2f}")
    print("Optimal Restaurant Setup:")
    for key, value in study.best_params.items():
        print(f"  - {key}: {value}")
    print("=" * 40)
